### ISSUE TITLE
请问作者，公式预览弹窗的字体颜色可以修改吗或者需要动哪里

### ISSUE THREAD

**Issue by devindang** [AntonVanke/Typora-Cement-Theme#2]
目前的这个预览效果貌似观感不佳，字体改成黑色或许好一点。
![image](https://picgo-devin.oss-cn-hangzhou.aliyuncs.com/Snipaste_2022-10-18_19-27-10.png)

**Comment by AntonVanke** [comment]
> 目前的这个预览效果貌似观感不佳，字体改成黑色或许好一点。 ![image](https://camo.githubusercontent.com/6d1121dcfb9f26212b01479306b879646b10b05f03226a048ddae11f4ab15d94/68747470733a2f2f706963676f2d646576696e2e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f536e6970617374655f323032322d31302d31385f31392d32372d31302e706e67)

确实有点难以区分，如果需要更改，需要在主题文件内添加：

```css
#math-inline-preview #math-inline-preview-content {
    color: <color>;
}
```

---

我稍后就会更新
