### ISSUE TITLE
代码块这里貌似有点问题，没有猜到什么原因导致的

### ISSUE THREAD

**Issue by devindang** [AntonVanke/Typora-Cement-Theme#3]
如图所示，绿色的这块是cement主题，下面的是github主题，后面这段莫名其妙加了棕色的背景
![imag](https://picgo-devin.oss-cn-hangzhou.aliyuncs.com/Snipaste_2022-10-18_20-03-19.png)

**Comment by AntonVanke** [comment]
刚才试了一下，`typora` 会将这段标记为错误代码

**Comment by AntonVanke** [comment]
> 如图所示，绿色的这块是cement主题，下面的是github主题，后面这段莫名其妙加了棕色的背景 ![imag](https://camo.githubusercontent.com/7cd63c7efa485ca457906ca69fd3f3064cb3344589bce7929f0c2e09319a3e92/68747470733a2f2f706963676f2d646576696e2e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f536e6970617374655f323032322d31302d31385f32302d30332d31392e706e67)

`CodeMirror` 将这行识别为错误代码，如需更改，可在主题文件内弱化显示：

```css
/*
https://github.com/AntonVanke/Typora-Cement-Theme/blob/main/cement.css#L822-L825
*/
.cm-s-inner span.cm-error {
    /*background: #ac4142;*/
    color: #505050
}
```

---

我稍后会更新
